import { JWT } from 'google-auth-library';

// env var values here are copied from service account credentials generated by google
// see "Authentication" section in docs for more info
export const serviceAccountAuth = new JWT({
  email: process.env.NEXT_PUBLIC_GOOGLE_SERVICE_ACCOUNT_EMAIL,
  key: process.env.NEXT_PUBLIC_GOOGLE_SERVICE_ACCOUNT_KEY,
  scopes: [ 'https://www.googleapis.com/auth/spreadsheets' ]
});
