import { JWT } from 'google-auth-library';

export const serviceAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: process.env.NEXT_PUBLIC_GOOGLE_SERVICE_ACCOUNT_EMAIL,
  key: process.env.NEXT_PUBLIC_GOOGLE_SERVICE_ACCOUNT_KEY,//.replace(/\\n/gm, '\n')
  scopes: [
    'https://www.googleapis.com/auth/spreadsheets',
  ],
});